default_platform(:android)

platform :android do
  desc "Build and deploy the Android app to the Play Store (internal track)"
  lane :deploy do
    Dir.chdir("..") do
      sh("flutter", "build", "appbundle", "--release")
    end

    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
